import { useEffect, useState } from "react";
import Head from "next/head";
import About from "@/components/About";
import Technologies from "@/components/Technologies";

import techs from "../data/techs.json";

import Applications from "@/components/Applications";
import Hero from "@/components/Hero";

export const getStaticProps = async (context: any) => {
  return {
    props: { techs: techs },
    revalidate: 43200,
  };
};

export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>Nick Buzzerio Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="preload"
          href="/fonts/RubikDistressed-Regular.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </Head>

      <main className="main flex flex-col items-center justify-center">
        <Hero />
        {/* <div className="hero flex h-screen flex-col items-center justify-center">
          <h1 className="text-shadow flex overflow-hidden pt-10 text-center text-5xl uppercase text-primary sm:text-6xl md:text-8xl lg:text-9xl">
            <span className="inline-block animate-fade opacity-0">
              Hi.&nbsp;
            </span>
            <span className="text-wrapper inline-block">
              <span className="inline-block animate-jump">
                I&apos;m
                <span className="text-shadow-white text-white-dark">
                  &nbsp;Nick
                </span>
                .
              </span>
            </span>
          </h1>
          <p className="tagline pt-[10%] pb-[20%] text-center text-4xl text-slate-300 transition-opacity md:text-6xl">
            <span className="relative inline-block py-1">
              {lineOne}
              <span className="line-one cursor hidden"> </span>
            </span>
            <br />
            <span className="relative inline-block py-1">
              {lineTwo}
              <span className="line-two cursor hidden"></span>
            </span>
          </p>
          <div className=""></div>
          <div className="scroll-button animate-bounce cursor-pointer text-5xl text-white">
            <a href="#about">
              <img
                src="/images/down-arrow.svg"
                alt=""
                className="arrow w-32 opacity-0 transition-opacity duration-1000"
              />
            </a>
          </div>
        </div> */}
        <About />
        <Technologies techs={techs} />
        <Applications />
      </main>
    </div>
  );
}
