import { useEffect, useState } from "react";
import Head from "next/head";
import About from "@/components/About";
import Technologies from "@/components/Technologies";

import techs from "../data/techs.json";
import Applications from "@/components/Applications";

export const getStaticProps = async (context: any) => {
  return {
    props: { techs: techs },
    revalidate: 43200,
  };
};

export default function Home() {
  const [lineOne, setLineOne] = useState("");
  const [lineTwo, setLineTwo] = useState("");
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const lineOneCursor =
      document.querySelector<HTMLSpanElement>(".line-one.cursor");
    const lineTwoCursor =
      document.querySelector<HTMLSpanElement>(".line-two.cursor");
    const tagline = document.querySelector<HTMLSpanElement>(".tagline");

    if (loaded) {
      setTimeout(() => {
        if (lineOne.length < textOne.length) {
          setLineOne(textOne.slice(0, lineOne.length + 1));
          if (lineOne.length + 1 === textOne.length) {
            lineOneCursor.style.display = "none";
            lineTwoCursor.style.display = "inline-block";
          }
        } else if (lineTwo.length < textTwo.length) {
          setLineTwo(textTwo.slice(0, lineTwo.length + 1));
          if (lineTwo.length + 1 === textTwo.length - 1) {
            tagline.style.textShadow = "0 0 7px #fff";
            tagline.style.transform = "scale(1.05)";
          } else if (lineTwo.length + 1 === textTwo.length) {
            lineTwoCursor.style.display = "none";
            tagline.style.transform = "scale(1.0)";
            document.querySelector<HTMLImageElement>(".arrow").style.opacity = '1';
          }
        }
      }, 50);
    } else {
      setTimeout(() => {
        lineOneCursor.style.display = "inline-block";
        setLoaded(true);
      }, 3000);
    }

    return () => {};
  }, [lineOne, lineTwo, loaded]);

  const textOne = "I develop full stack";
  const textTwo = "applications for the web.";

  return (
    <div className="bg-black">
      <Head>
        <title>Nick Buzzerio Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main flex flex-col items-center justify-center">
        <div className="hero h-screen flex flex-col items-center justify-center">
          <h1 className="text-shadow flex text-center text-5xl sm:text-6xl uppercase text-primary md:text-8xl lg:text-9xl pt-10 overflow-hidden">
            <span className="animate-fade opacity-0 inline-block">Hi.&nbsp;</span>
            <span className="text-wrapper inline-block">
              <span className="inline-block animate-jump">
                I&apos;m
                <span className="text-shadow-white text-white-dark">&nbsp;Nick</span>.
              </span>
            </span>
          </h1>
          <p className="tagline text-center text-4xl text-slate-300 transition-opacity md:text-6xl pt-[10%] pb-[20%]">
            <span className="inline-block py-1">
              {lineOne}
              <span className="line-one cursor hidden"> </span>
            </span>
            <br />
            <span className="inline-block py-1">
              {lineTwo}
              <span className="line-two cursor hidden"></span>
            </span>
          </p>
          <div className=""></div>
          <div className="scroll-button animate-bounce cursor-pointer text-5xl text-white">
            <a href="#about">
              <img
                src="/images/down-arrow.svg"
                alt=""
                className="arrow w-32 opacity-0 transition-opacity duration-1000"
              />
            </a>
          </div>
        </div>
        <About />
        <Technologies techs={techs} />
        <Applications />
      </main>
    </div>
  );
}
