import Head from 'next/head'

export default function Home() {


  return (
    <div className='bg-blue-600 h-screen'>
      <Head>
        <title>Nick Buzzerio Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
        <h1 className='text-7xl text-green-400 text-center'>
          Hi, I'm Nick.
        </h1>

      </main>
    </div>
  )
}
